export class Constants {
  public static readonly FONT_SIZE_12 = '12fp';
  public static readonly FONT_SIZE_14 = '14fp';
  public static readonly FONT_SIZE_18 = '18fp';
  public static readonly THEME_COLOR = '#94B982';
  public static readonly FONT_COLOR_LEVEL1 = '#E6000000';
  public static readonly FONT_COLOR_1_INVERT = '#FFFFFF';
  public static readonly FONT_COLOR_LEVEL2 = '#99000000';
  public static readonly FONT_COLOR_LEVEL3 = '#9e9e9e';
  public static readonly DIVIDER_COLOR = '#33000000';
  public static readonly WARNING_COLOR = '#E84026';
  public static readonly BACKGROUND_COLOR = '#FFFFFF';
  public static readonly WEEK_LABEL_LIST: string[] = [
    '日',
    '一',
    '二',
    '三',
    '四',
    '五',
    '六',
  ];
}
